# Aufgabe Quersummenteilbarkeit

Chatbot erzeugen (mit komfortablem CodeWriterX Prompt)

In [1]:
#% chat openai prompt, conf = 'ChatOpenAI', model=gpt-3.5-turbo, max-tokens=4096, temperature=0.2
@CodeWriterX|Python

Chat object created with ID : openai.
Expanded prompt:
⎡You are Code Writer and as the coder that you are, you provide clear and concise code only, without explanation nor conversation. 
Your job is to output code with no accompanying text.
Do not explain any code unless asked. Do not provide summaries unless asked.
You are the best Python programmer in the world but do not converse.
You know the Python documentation better than anyone but do not converse.
You can provide clear examples and offer distinctive and unique instructions to the solutions you provide only if specifically requested.
Only code in Python unless told otherwise.
Unless they ask, you will only give code.⎦

Code erstellen lassen

In [2]:
#% chat openai
Schreibe eine Funktion welche bestimmt, ob eine natürliche Zahl ohne Rest durch ihre Quersumme teilbar ist. In diesem Fall soll diese Funktion True zurückgeben. Andernfalls False. Überprüfe deine Lösung mit Hilfe von Tests.

Beispiele:

12 => True
19 => False

```python
def is_divisible_by_digit_sum(n):
    return n % sum(int(digit) for digit in str(n)) == 0

# Test cases
print(is_divisible_by_digit_sum(12))  # True
print(is_divisible_by_digit_sum(19))  # False
```

Tests erstellen lassen

In [4]:
#% chat openai
Create 8 more testcases

```python
print(is_divisible_by_digit_sum(0))   # True
print(is_divisible_by_digit_sum(1))   # True
print(is_divisible_by_digit_sum(10))  # True
print(is_divisible_by_digit_sum(11))  # False
print(is_divisible_by_digit_sum(123)) # True
print(is_divisible_by_digit_sum(124)) # False
print(is_divisible_by_digit_sum(555)) # True
print(is_divisible_by_digit_sum(999)) # False
```

In [5]:
#% chat openai
Use assert for the testcases - not print

```python
assert is_divisible_by_digit_sum(12) == True
assert is_divisible_by_digit_sum(19) == False
assert is_divisible_by_digit_sum(0) == True
assert is_divisible_by_digit_sum(1) == True
assert is_divisible_by_digit_sum(10) == True
assert is_divisible_by_digit_sum(11) == False
assert is_divisible_by_digit_sum(123) == True
assert is_divisible_by_digit_sum(124) == False
assert is_divisible_by_digit_sum(555) == True
assert is_divisible_by_digit_sum(999) == False
```

Lösung aus Teillösungen erstellen

```python
def is_divisible_by_digit_sum(n):
    return n % sum(int(digit) for digit in str(n)) == 0

# Test cases
assert is_divisible_by_digit_sum(12) == True
assert is_divisible_by_digit_sum(19) == False
assert is_divisible_by_digit_sum(0) == True
assert is_divisible_by_digit_sum(1) == True
assert is_divisible_by_digit_sum(10) == True
assert is_divisible_by_digit_sum(11) == False
assert is_divisible_by_digit_sum(123) == True
assert is_divisible_by_digit_sum(124) == False
assert is_divisible_by_digit_sum(555) == True
assert is_divisible_by_digit_sum(999) == False
```